### ISSUE TITLE
Feature Request: Different themes per Highlight.

### ISSUE THREAD

**Issue by BadPingHere** [metonym/svelte-highlight#313] opened 2023-12-24 00:30 UTC
Imagine a world where we could have separate themes for each Highlight we have, where we could grasp the beauty of not only highlightjs, but svelte-highlight as a whole. I believe that we should move towards that utopia.

**Comment by metonym** [comment] 2023-12-24 04:01
Duplicate of #233

**Closed by metonym** 2023-12-24 04:01 UTC
